### ISSUE TITLE
Network name resolution usually needs /etc/nsswitch.conf

### ISSUE THREAD

**Issue by locallycompact** [NixOS/docker#7]
Hi, I'm using this nix docker to build other dockers in gitlab CI, but it's failing to run the servant test suite because of errors like the following:

```
(ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: 
AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, 
addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>},
host name: Just "localhost", service name: Just "34263"): does not exist (Name or service not known)))
```

Here is the full log: https://gitlab.com/zenhaskell/infra-dockers/-/jobs/173325822

/etc/hosts looks fine to me but here it is in full

```
$ cat /etc/hostname
runner-ed2dce3a-project-7321855-concurrent-0
$ cat /etc/hosts
127.0.0.1        localhost
::1        localhost ip6-localhost ip6-loopback
fe00::0        ip6-localnet
ff00::0        ip6-mcastprefix
ff02::1        ip6-allnodes
ff02::2        ip6-allrouters
172.17.0.3        docker 41ed789b04a5 runner-ed2dce3a-project-7321855-concurrent-0-docker-0
172.17.0.4        runner-ed2dce3a-project-7321855-concurrent-0
```

**Comment by thoughtpolice** [comment]
This is likely because you do not have `/etc/nsswitch.conf` configured inside the built Docker container, so glibc doesn't know (how|what sources to use) for performing name resolution -- this is a gotcha that also just bit me.

My solution, as I am using `pkgs.dockerTools`, is to just include a package into the contents of the image which contains a simple `nsswitch.conf` to use DNS/hosts file resolution, in that order

```
## needed for container/host resolution
nsswitch-conf = pkgs.writeTextFile {
  name = "nsswitch.conf";
  text = "hosts: dns files";
  destination = "/etc/nsswitch.conf";
};
```

---

In your case, simply putting `hosts: dns files` into the container (somehow) should be sufficient to work around this, I think.
